# Generated by Django 5.0.6 on 2024-05-14 20:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Student", "0003_alter_student_information_phone"),
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allocate_Student_to_Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "room",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="room_allocated",
                        to="home.room",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_allocated",
                        to="Student.student_information",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "انتساب دانشجو به اتاق ",
                "db_table": "Allocate_Student_to_Room",
            },
        ),
    ]
