# Generated by Django 5.0.6 on 2024-05-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="شماره اتاق")),
                ("capacity", models.IntegerField(default=6, verbose_name="ظرفیت اتاق")),
                ("floor", models.IntegerField(default=1, verbose_name="شماره طبقه")),
            ],
            options={
                "verbose_name_plural": "اتاق ها خوابگاه",
                "db_table": "Room",
                "ordering": ["name"],
            },
        ),
    ]
