# Generated by Django 5.0.6 on 2024-05-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student_Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "student_number",
                    models.CharField(max_length=100, verbose_name="شماره دانشجویی"),
                ),
                (
                    "phone",
                    models.CharField(max_length=11, verbose_name="شماره دانشجویی"),
                ),
            ],
            options={
                "verbose_name_plural": "مشخصات دانشجویان",
                "db_table": "Student_Information",
            },
        ),
    ]
