# Generated by Django 5.0.6 on 2024-05-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Student", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student_information",
            name="phone",
            field=models.CharField(
                default=0, max_length=11, verbose_name="شماره دانشجویی"
            ),
        ),
        migrations.AlterField(
            model_name="student_information",
            name="student_number",
            field=models.CharField(
                default=0, max_length=100, verbose_name="شماره دانشجویی"
            ),
        ),
    ]
