# Generated by Django 5.0.6 on 2024-05-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Student", "0002_alter_student_information_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student_information",
            name="phone",
            field=models.CharField(
                default=0, max_length=11, verbose_name="شماره همراه"
            ),
        ),
    ]
